### PR TITLE
Implement `serde::Serialize` and `serde::Deserialize` for all types.

### PR DESCRIPTION
**Pull request by Banyc**
Implement #2.

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Looks good. But why `serde = ["dep:serde"]` instead of `serde = ["serde"]`?

**Comment by RazrFalcon** [comment]
And it fails on old Rust. I guess we should remove `serde = ["dep:serde"]` completely. `serde`, by being an optional dependency, will automatically become a feature.

**Comment by Banyc** [comment]
Thanks for the information! I have fixed the issue now.

**Comment by RazrFalcon** [comment]
>supported edition values are `2015` or `2018`, but `2021` is unknown

I guess we have to bump MSRV to 1.56 as well. You can do it in `.github/workflows/main.yml` and bump it in the README as well.

**Comment by Banyc** [comment]
I have also upgraded the `edition` from `2018` to `2021` and added the `rust-version` field to specify the MSRV in `Cargo.toml` according to the [1.56.0 release blog post](https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html).

**Comment by RazrFalcon** [comment]
Thanks!

**Pull request merged**
